version: '3.8' 

services: 
  wip-main: 
    image: 2mukee/wip-main
    depends_on:
     - wip-db
    ports: 
     - 17260:17260 
    networks:
     - wip-router
    environment: 
     - TZ=Asia/Seoul 
     - NODE_ENV=production
    deploy: 
      mode: replicated 
      replicas: 10 
      update_config: 
        parallelism: 10 
        delay: 10s 
        order: start-first 
        failure_action: rollback 

  wip-db: 
    image: mongo
    expose: 
      - 27017
    networks:
      - wip-router
    environment:
     - TZ=Asia/Seoul
     - MONGO_INIT_DB_DATABASE=whatispill
    volumes: 
     - /mnt/d/server/wip-main/data:/data/db 