version: '3.8' 

services: 
main: 
  image: 2mukee/wip-main:0.1 
  ports: 
   - 17260:17260 
  environment: 
   - TZ=Asia/Seoul 
  deploy: 
   mode: replicated 
   replicas: 10 
   update_config: 
    parallelism: 10 
    delay: 10s 
    order: start-first 
    failure_action: rollback 

db: 
  image: 2mukee/wip-db:0.1 
  environment: 
   - TZ=Asia/Seoul 
  volumes: 
   - /mnt/d/server/wip-main/data:/data/db 
  environment: 
   - TZ=Asia/Seoul 