name: build

on:
    workflow_call:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: build_project
        run: yarn install && tsc --build