name: what-is-pill-main-server-cicd

run-name: ${{ github.actor }} run cicd

on:
  workflow_dispatch:
    inputs:
      deploy_mode:
        description: 'set deploy mode'
        required: true
        default: 'BUILD-ONLY'
        type: choice
        options:
          - STAND-ALONE
          - SINGLE-CONTAINER
          - DOCKER-COMPOSE
  
env:
  WORK_PATH: ${{ secrets.WORK_DIR_MAIN }}

jobs:
  run-pull:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
    #   - uses: actions/checkout@v4
    #   - uses: webfactory/ssh-agent@v0.9.0
    #     with:
    #       ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    #   - uses: appleboy/ssh-action@master
    #     with:
    #       host: ${{ secrets.SSH_HOST }}
    #       username: ${{ secrets.SSH_USER }}
    #       key: ${{ secrets.SSH_PRIVATE_KEY }}
    #       port: ${{ secrets.SSH_PORT }}
    #       script: |
    #         echo success
      - name: install ssh keys
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: connect ssh
        run: ssh -vT ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}
      - name: test
        run: echo ${{ github.event.intpus.deploy_mode }}
      - name: cleanup
        run: rm -rf ~/.ssh