name: what-is-pill-main-server-cicd

run-name: ${{ github.actor }}-run-cicd

on:
  workflow_dispatch:
    inputs:
      deploy_mode:
        description: 'Choose deploy mode'
        required: true
        default: 'DOCKER-COMPOSE'
        type: choice
        options:
          - STAND-ALONE
          - SINGLE-CONTAINER
          - DOCKER-COMPOSE

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - if: contains(fromJSON('["DOCKER-COMPOSE"]'), github.event.inputs.deploy_mode)
        name: run multiple mode
        run: |
          ssh -o ServerAliveInterval=3600 -vT ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
          "cd ${{ secrets.WORK_DIR_MAIN }} && \
           git pull && \
           cd ${{ secrets.WORK_DIR_INFRA }} && \
           bash run.sh ${{ github.event.inputs.deploy_mode }}"

      - name: cleanup
        run: rm -rf ~/.ssh
